version: '3'
services:
  surrealdb:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/surrealdb/data
  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"

volumes:
  db_data:
  redis_data: