### Test signing up as a new discord member
POST http://localhost:8080/discord/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZHMiLCJzdWIiOiJib3QiLCJhdWQiOlsiYm90Il0sImlhdCI6MTcxMDEwMjU3MX0.Y-Uwgv1pyfx8LdAOxBaZuhHYFAg2HcpwmX1xvvtNbUo
Content-Type: application/json

{
  "id": "672835870080106509",
  "nick": "NoBypass",
  "name": "nobypass"
}

### Test daily claiming
PATCH http://localhost:8080/discord/daily/672835870080106509
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZHMiLCJzdWIiOiJib3QiLCJhdWQiOlsiYm90Il0sImlhdCI6MTcxMDEwMjU3MX0.Y-Uwgv1pyfx8LdAOxBaZuhHYFAg2HcpwmX1xvvtNbUo

### Test logging in as discord bot
POST http://localhost:8080/discord/bot-login
Content-Type: application/json

{
  "pwd": "1234"
}

### Test leaderboard
GET http://localhost:8080/discord/leaderboard/0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZHMiLCJzdWIiOiJib3QiLCJhdWQiOlsiYm90Il0sImlhdCI6MTcxMDEwMjU3MX0.Y-Uwgv1pyfx8LdAOxBaZuhHYFAg2HcpwmX1xvvtNbUo

### Test getting user info
GET http://localhost:8080/discord/member/672835870080106509
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZHMiLCJzdWIiOiJib3QiLCJhdWQiOlsiYm90Il0sImlhdCI6MTcxMDEwMjU3MX0.Y-Uwgv1pyfx8LdAOxBaZuhHYFAg2HcpwmX1xvvtNbUo

### Test revoking a discord member
DELETE http://localhost:8080/discord/revoke/672835870080106509
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmZHMiLCJzdWIiOiJib3QiLCJhdWQiOlsiYm90Il0sImlhdCI6MTcxMDEwMjU3MX0.Y-Uwgv1pyfx8LdAOxBaZuhHYFAg2HcpwmX1xvvtNbUo
