image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


build:
  image: gradle:jdk17
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    reports:
      junit: build/test-results/test/**/TEST-*.xml

test:
  image: gradle:jdk17
  stage: test
  script:
    - gradle check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

after_script:
  - echo "End CI"