// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NoBypass/fds/internal/adapter"
	"github.com/NoBypass/fds/internal/adapter/operations"
	"github.com/NoBypass/fds/internal/app"
	"github.com/NoBypass/fds/internal/port/controller"
	"github.com/NoBypass/mincache"
)

// Injectors from wire.go:

func initScrimsController(db adapter.Database, cache *mincache.Cache) *controller.ScrimsController {
	scrimsRepository := operations.NewScrimsRepository(db)
	scrimsAPI := adapter.NewScrimsAPI(cache)
	mojangAPI := adapter.NewMojangAPI(cache)
	minecraftUseCase := app.NewMinecraftUseCase(scrimsRepository, scrimsAPI, mojangAPI)
	scrimsController := controller.NewScrimsController(minecraftUseCase)
	return scrimsController
}

func initPlayerController(db adapter.Database, cache *mincache.Cache) *controller.PlayerController {
	scrimsRepository := operations.NewScrimsRepository(db)
	scrimsAPI := adapter.NewScrimsAPI(cache)
	mojangAPI := adapter.NewMojangAPI(cache)
	minecraftUseCase := app.NewMinecraftUseCase(scrimsRepository, scrimsAPI, mojangAPI)
	playerController := controller.NewPlayerController(minecraftUseCase)
	return playerController
}
