package domain

type HypixelPlayerResp struct {
	Success bool `json:"success"`
	Player  struct {
		UUID                string   `json:"uuid"`
		FirstLogin          int64    `json:"firstLogin"`
		PlayerName          string   `json:"playername"`
		DisplayName         string   `json:"displayname"`
		AchievementsOneTime []string `json:"achievementsOneTime"`
		NetworkExp          float64  `json:"networkExp"`
		UserLanguage        string   `json:"userLanguage"`
		Challenges          struct {
			AllTime map[string]int `json:"all_time"`
		} `json:"challenges"`
		AchievementTracking    []string                  `json:"achievementTracking"`
		ParkourCheckpointBests map[string]map[string]int `json:"parkourCheckpointBests"`
		Karma                  int                       `json:"karma"`
		ParkourCompletions     map[string][]struct {
			TimeStart int64 `json:"timeStart"`
			TimeTook  int64 `json:"timeTook"`
		} `json:"parkourCompletions"`
		AchievementPoints int `json:"achievementPoints"`
		Quests            map[string]struct {
			Completions []struct {
				Time int64 `json:"time"`
			} `json:"completions"`
			Active struct {
				Objectives map[string]int `json:"objectives"`
				Started    int64          `json:"started"`
			} `json:"active"`
		}
		NewPackageRank        string `json:"newPackageRank"`
		LevelUpVIP            int64  `json:"levelUp_VIP"`
		LevelUpPlus           int64  `json:"levelUp_PLUS"`
		LevelUpMVP            int64  `json:"levelUp_MVP"`
		LevelUpMVPPlus        int64  `json:"levelUp_MVP_PLUS"`
		LastClaimedReward     int64  `json:"lastClaimedReward"`
		RewardHighScore       int64  `json:"rewardHighScore"`
		RewardScore           int64  `json:"rewardScore"`
		RewardStreak          int64  `json:"rewardStreak"`
		TotalDailyRewards     int64  `json:"totalDailyRewards"`
		TotalRewards          int64  `json:"totalRewards"`
		Tourney               any    `json:"tourney"`
		AchievementRewardsNew map[string]int64
		SocialMedia           struct {
			Links map[string]string `json:"links"`
		} `json:"socialMedia"`
		RankPlusColor                string `json:"rankPlusColor"`
		MonthlyPackageRank           string `json:"monthlyPackageRank"`
		MostRecentMonthlyPackageRank string `json:"mostRecentMonthlyPackageRank"`
		MonthlyRankColor             string `json:"monthlyRankColor"`
		GiftingMeta                  struct {
			BundlesReceived     int `json:"bundlesReceived"`
			RealBundlesReceived int `json:"realBundlesReceived"`
			BundlesGiven        int `json:"bundlesGiven"`
			RealBundlesGiven    int `json:"realBundlesGiven"`
			GiftsGiven          int `json:"giftsGiven"`
			RanksGiven          int `json:"ranksGiven"`
		} `json:"giftingMeta"`
		/*
			Stats struct {
				// TODO: BuildBattle, TrueCombat, SkyWars, SuperSmash, SpeedUHC, MCGO, Battleground, Arcade, MurderMystery, TNTGames, HungerGames, SkyClash, Quake, GingerBread, VampireZ, Paintball, Duels, Pit, UHC, Walls3, SkyBlock, Arena, Walls, Legacy, Housing, MainLobby, WoolGames
					Bedwars struct {
						Experience                                       int      `json:"Experience"`
						GoldResourcesCollectedBedwars                    int      `json:"gold_resources_collected_bedwars"`
						VoidDeathsBedwars                                int      `json:"void_deaths_bedwars"`
						VoidKillsBedwars                                 int      `json:"void_kills_bedwars"`
						DeathsBedwars                                    int      `json:"deaths_bedwars"`
						ResourcesCollectedBedwars                        int      `json:"resources_collected_bedwars"`
						FourFourVoidKillsBedwars                         int      `json:"four_four_void_kills_bedwars"`
						FourFourKillsBedwars                             int      `json:"four_four_kills_bedwars"`
						Coins                                            int      `json:"coins"`
						GamesPlayedBedwars                               int      `json:"games_played_bedwars"`
						FourFourDeathsBedwars                            int      `json:"four_four_deaths_bedwars"`
						FourFourGoldResourcesCollectedBedwars            int      `json:"four_four_gold_resources_collected_bedwars"`
						FourFourEntityAttackDeathsBedwars                int      `json:"four_four_entity_attack_deaths_bedwars"`
						FourFourLossesBedwars                            int      `json:"four_four_losses_bedwars"`
						FourFourIronResourcesCollectedBedwars            int      `json:"four_four_iron_resources_collected_bedwars"`
						KillsBedwars                                     int      `json:"kills_bedwars"`
						EntityAttackKillsBedwars                         int      `json:"entity_attack_kills_bedwars"`
						FourFourGamesPlayedBedwars                       int      `json:"four_four_games_played_bedwars"`
						EntityAttackDeathsBedwars                        int      `json:"entity_attack_deaths_bedwars"`
						LossesBedwars                                    int      `json:"losses_bedwars"`
						ItemsPurchasedBedwars                            int      `json:"items_purchased_bedwars"`
						FourFourResourcesCollectedBedwars                int      `json:"four_four_resources_collected_bedwars"`
						FourFourVoidDeathsBedwars                        int      `json:"four_four_void_deaths_bedwars"`
						FourFourItemsPurchasedBedwars                    int      `json:"four_four_items_purchased_bedwars"`
						IronResourcesCollectedBedwars                    int      `json:"iron_resources_collected_bedwars"`
						FourFourEntityAttackKillsBedwars                 int      `json:"four_four_entity_attack_kills_bedwars"`
						FourFourProjectileDeathsBedwars                  int      `json:"four_four_projectile_deaths_bedwars"`
						DiamondResourcesCollectedBedwars                 int      `json:"diamond_resources_collected_bedwars"`
						FourFourWinsBedwars                              int      `json:"four_four_wins_bedwars"`
						WinsBedwars                                      int      `json:"wins_bedwars"`
						ProjectileDeathsBedwars                          int      `json:"projectile_deaths_bedwars"`
						FourFourDiamondResourcesCollectedBedwars         int      `json:"four_four_diamond_resources_collected_bedwars"`
						FinalDeathsBedwars                               int      `json:"final_deaths_bedwars"`
						EmeraldResourcesCollectedBedwars                 int      `json:"emerald_resources_collected_bedwars"`
						FourFourFinalDeathsBedwars                       int      `json:"four_four_final_deaths_bedwars"`
						FourFourVoidFinalDeathsBedwars                   int      `json:"four_four_void_final_deaths_bedwars"`
						FourFourBedsLostBedwars                          int      `json:"four_four_beds_lost_bedwars"`
						BedsLostBedwars                                  int      `json:"beds_lost_bedwars"`
						VoidFinalDeathsBedwars                           int      `json:"void_final_deaths_bedwars"`
						FourFourEmeraldResourcesCollectedBedwars         int      `json:"four_four_emerald_resources_collected_bedwars"`
						EntityAttackFinalDeathsBedwars                   int      `json:"entity_attack_final_deaths_bedwars"`
						FourFourEntityAttackFinalDeathsBedwars           int      `json:"four_four_entity_attack_final_deaths_bedwars"`
						FourFourEntityExplosionKillsBedwars              int      `json:"four_four_entity_explosion_kills_bedwars"`
						EntityExplosionKillsBedwars                      int      `json:"entity_explosion_kills_bedwars"`
						FallDeathsBedwars                                int      `json:"fall_deaths_bedwars"`
						FourFourFallDeathsBedwars                        int      `json:"four_four_fall_deaths_bedwars"`
						EntityAttackFinalKillsBedwars                    int      `json:"entity_attack_final_kills_bedwars"`
						FourFourEntityAttackFinalKillsBedwars            int      `json:"four_four_entity_attack_final_kills_bedwars"`
						FinalKillsBedwars                                int      `json:"final_kills_bedwars"`
						FourFourFinalKillsBedwars                        int      `json:"four_four_final_kills_bedwars"`
						BedwarsOpenedCommons                             int      `json:"Bedwars_openedCommons"`
						ChestHistoryNew                                  []string `json:"chest_history_new"`
						BedwarsOpenedChests                              int      `json:"Bedwars_openedChests"`
						BedwarsOpenedRares                               int      `json:"Bedwars_openedRares"`
						BedwarsOpenedEpics                               int      `json:"Bedwars_openedEpics"`
						ActiveKillEffect                                 string   `json:"activeKillEffect"`
						ActiveSprays                                     string   `json:"activeSprays"`
						ActiveGlyph                                      string   `json:"activeGlyph"`
						FourFourBedsBrokenBedwars                        int      `json:"four_four_beds_broken_bedwars"`
						BedsBrokenBedwars                                int      `json:"beds_broken_bedwars"`
						EightTwoVoidDeathsBedwars                        int      `json:"eight_two_void_deaths_bedwars"`
						EightTwoResourcesCollectedBedwars                int      `json:"eight_two_resources_collected_bedwars"`
						EightTwoKillsBedwars                             int      `json:"eight_two_kills_bedwars"`
						EightTwoIronResourcesCollectedBedwars            int      `json:"eight_two_iron_resources_collected_bedwars"`
						EightTwoVoidKillsBedwars                         int      `json:"eight_two_void_kills_bedwars"`
						EightTwoFinalDeathsBedwars                       int      `json:"eight_two_final_deaths_bedwars"`
						EightTwoVoidFinalDeathsBedwars                   int      `json:"eight_two_void_final_deaths_bedwars"`
						EightTwoDeathsBedwars                            int      `json:"eight_two_deaths_bedwars"`
						EightTwoGamesPlayedBedwars                       int      `json:"eight_two_games_played_bedwars"`
						EightTwoItemsPurchasedBedwars1                   int      `json:"eight_two_items_purchased_bedwars"`
						EightTwoBedsLostBedwars                          int      `json:"eight_two_beds_lost_bedwars"`
						EightTwoEntityAttackDeathsBedwars                int      `json:"eight_two_entity_attack_deaths_bedwars"`
						EightTwoGoldResourcesCollectedBedwars            int      `json:"eight_two_gold_resources_collected_bedwars"`
						EightTwoLossesBedwars                            int      `json:"eight_two_losses_bedwars"`
						EightTwoEntityAttackFinalDeathsBedwars           int      `json:"eight_two_entity_attack_final_deaths_bedwars"`
						EightOneItemsPurchasedBedwars                    int      `json:"eight_one_items_purchased_bedwars"`
						EightOneVoidDeathsBedwars                        int      `json:"eight_one_void_deaths_bedwars"`
						EightOneDeathsBedwars                            int      `json:"eight_one_deaths_bedwars"`
						EightOneGamesPlayedBedwars                       int      `json:"eight_one_games_played_bedwars"`
						EightOneLossesBedwars                            int      `json:"eight_one_losses_bedwars"`
						EightOneIronResourcesCollectedBedwars            int      `json:"eight_one_iron_resources_collected_bedwars"`
						EightOneResourcesCollectedBedwars                int      `json:"eight_one_resources_collected_bedwars"`
						EightOneGoldResourcesCollectedBedwars            int      `json:"eight_one_gold_resources_collected_bedwars"`
						EightOneBedsLostBedwars                          int      `json:"eight_one_beds_lost_bedwars"`
						EightOneFinalDeathsBedwars                       int      `json:"eight_one_final_deaths_bedwars"`
						EightOneEntityAttackFinalDeathsBedwars           int      `json:"eight_one_entity_attack_final_deaths_bedwars"`
						FourFourVoidFinalKillsBedwars                    int      `json:"four_four_void_final_kills_bedwars"`
						VoidFinalKillsBedwars                            int      `json:"void_final_kills_bedwars"`
						EightTwoEntityAttackKillsBedwars                 int      `json:"eight_two_entity_attack_kills_bedwars"`
						BedwarsOpenedLegendaries                         int      `json:"Bedwars_openedLegendaries"`
						CastleBedsLostBedwars                            int      `json:"castle_beds_lost_bedwars"`
						CastleDeathsBedwars                              int      `json:"castle_deaths_bedwars"`
						CastleGamesPlayedBedwars                         int      `json:"castle_games_played_bedwars"`
						CastleFinalDeathsBedwars                         int      `json:"castle_final_deaths_bedwars"`
						CastleVoidFinalDeathsBedwars                     int      `json:"castle_void_final_deaths_bedwars"`
						CastleItemsPurchasedBedwars                      int      `json:"castle_items_purchased_bedwars"`
						CastleGoldResourcesCollectedBedwars              int      `json:"castle_gold_resources_collected_bedwars"`
						CastleResourcesCollectedBedwars                  int      `json:"castle_resources_collected_bedwars"`
						CastleEntityAttackDeathsBedwars                  int      `json:"castle_entity_attack_deaths_bedwars"`
						CastleLossesBedwars                              int      `json:"castle_losses_bedwars"`
						CastleVoidDeathsBedwars                          int      `json:"castle_void_deaths_bedwars"`
						CastleIronResourcesCollectedBedwars              int      `json:"castle_iron_resources_collected_bedwars"`
						FallFinalDeathsBedwars                           int      `json:"fall_final_deaths_bedwars"`
						FourFourFallFinalDeathsBedwars                   int      `json:"four_four_fall_final_deaths_bedwars"`
						FourThreeVoidKillsBedwars                        int      `json:"four_three_void_kills_bedwars"`
						FourThreeEntityAttackKillsBedwars                int      `json:"four_three_entity_attack_kills_bedwars"`
						FourThreeIronResourcesCollectedBedwars           int      `json:"four_three_iron_resources_collected_bedwars"`
						FourThreeEntityAttackFinalDeathsBedwars          int      `json:"four_three_entity_attack_final_deaths_bedwars"`
						FourThreeGamesPlayedBedwars                      int      `json:"four_three_games_played_bedwars"`
						FourThreeItemsPurchasedBedwars                   int      `json:"four_three_items_purchased_bedwars"`
						FourThreeVoidDeathsBedwars                       int      `json:"four_three_void_deaths_bedwars"`
						FourThreeEntityAttackDeathsBedwars               int      `json:"four_three_entity_attack_deaths_bedwars"`
						FourThreeBedsLostBedwars                         int      `json:"four_three_beds_lost_bedwars"`
						FourThreeGoldResourcesCollectedBedwars           int      `json:"four_three_gold_resources_collected_bedwars"`
						FourThreeDeathsBedwars                           int      `json:"four_three_deaths_bedwars"`
						FourThreeLossesBedwars                           int      `json:"four_three_losses_bedwars"`
						FourThreeKillsBedwars                            int      `json:"four_three_kills_bedwars"`
						FourThreeFinalDeathsBedwars                      int      `json:"four_three_final_deaths_bedwars"`
						FourThreeResourcesCollectedBedwars               int      `json:"four_three_resources_collected_bedwars"`
						Favourites2                                      string   `json:"favourites_2"`
						FourThreeFallDeathsBedwars                       int      `json:"four_three_fall_deaths_bedwars"`
						FourThreePermanentItemsPurchasedBedwars          int      `json:"four_three_permanent_items_purchased_bedwars"`
						EightTwoPermanentItemsPurchasedBedwars           int      `json:"eight_two_permanent_items_purchased_bedwars"`
						EightOnePermanentItemsPurchasedBedwars           int      `json:"eight_one_permanent_items_purchased_bedwars"`
						FallFinalKillsBedwars                            int      `json:"fall_final_kills_bedwars"`
						FourFourFallFinalKillsBedwars                    int      `json:"four_four_fall_final_kills_bedwars"`
						EntityExplosionDeathsBedwars                     int      `json:"entity_explosion_deaths_bedwars"`
						FourFourEntityExplosionDeathsBedwars             int      `json:"four_four_entity_explosion_deaths_bedwars"`
						FallKillsBedwars                                 int      `json:"fall_kills_bedwars"`
						FourFourFallKillsBedwars                         int      `json:"four_four_fall_kills_bedwars"`
						BedwarsHalloweenBoxes                            int      `json:"bedwars_halloween_boxes"`
						FreeEventKeyBedwarsHalloweenBoxes2018            bool     `json:"free_event_key_bedwars_halloween_boxes_2018"`
						SpookyOpenAch                                    int      `json:"spooky_open_ach"`
						ActiveIslandTopper                               string   `json:"activeIslandTopper"`
						FourThreeWinsBedwars                             int      `json:"four_three_wins_bedwars"`
						FourThreeBedsBrokenBedwars                       int      `json:"four_three_beds_broken_bedwars"`
						FourThreeEntityAttackFinalKillsBedwars           int      `json:"four_three_entity_attack_final_kills_bedwars"`
						FourThreeFinalKillsBedwars                       int      `json:"four_three_final_kills_bedwars"`
						FourThreeVoidFinalDeathsBedwars                  int      `json:"four_three_void_final_deaths_bedwars"`
						LastTourneyAd                                    int64    `json:"lastTourneyAd"`
						FourFourProjectileKillsBedwars                   int      `json:"four_four_projectile_kills_bedwars"`
						ProjectileKillsBedwars                           int      `json:"projectile_kills_bedwars"`
						BedwarsLunarBoxes                                int      `json:"bedwars_lunar_boxes"`
						FreeEventKeyBedwarsLunarBoxes2019                bool     `json:"free_event_key_bedwars_lunar_boxes_2019"`
						ActiveNPCSkin                                    string   `json:"activeNPCSkin"`
						ActiveDeathCry                                   string   `json:"activeDeathCry"`
						BedwarsEasterBoxes                               int      `json:"bedwars_easter_boxes"`
						FreeEventKeyBedwarsEasterBoxes2019               bool     `json:"free_event_key_bedwars_easter_boxes_2019"`
						FavoriteSlots                                    string   `json:"favorite_slots"`
						ActiveProjectileTrail                            string   `json:"activeProjectileTrail"`
						EntityExplosionFinalDeathsBedwars                int      `json:"entity_explosion_final_deaths_bedwars"`
						FourFourEntityExplosionFinalDeathsBedwars        int      `json:"four_four_entity_explosion_final_deaths_bedwars"`
						ActiveKillMessages                               string   `json:"activeKillMessages"`
						SelectedUltimate                                 string   `json:"selected_ultimate"`
						FourFourUltimateItemsPurchasedBedwars            int      `json:"four_four_ultimate_items_purchased_bedwars"`
						FourFourUltimateDeathsBedwars                    int      `json:"four_four_ultimate_deaths_bedwars"`
						FourFourUltimateGamesPlayedBedwars               int      `json:"four_four_ultimate_games_played_bedwars"`
						FourFourUltimateGoldResourcesCollectedBedwars    int      `json:"four_four_ultimate_gold_resources_collected_bedwars"`
						FourFourUltimateIronResourcesCollectedBedwars    int      `json:"four_four_ultimate_iron_resources_collected_bedwars"`
						FourFourUltimateLossesBedwars                    int      `json:"four_four_ultimate_losses_bedwars"`
						FourFourUltimateResourcesCollectedBedwars        int      `json:"four_four_ultimate_resources_collected_bedwars"`
						FourFourUltimateVoidDeathsBedwars                int      `json:"four_four_ultimate_void_deaths_bedwars"`
						FourThreeEmeraldResourcesCollectedBedwars        int      `json:"four_three_emerald_resources_collected_bedwars"`
						FourThreeVoidFinalKillsBedwars                   int      `json:"four_three_void_final_kills_bedwars"`
						FourThreeDiamondResourcesCollectedBedwars        int      `json:"four_three_diamond_resources_collected_bedwars"`
						FourThreeProjectileDeathsBedwars                 int      `json:"four_three_projectile_deaths_bedwars"`
						FreeEventKeyBedwarsHalloweenBoxes2019            bool     `json:"free_event_key_bedwars_halloween_boxes_2019"`
						FreeEventKeyBedwarsChristmasBoxes2019            bool     `json:"free_event_key_bedwars_christmas_boxes_2019"`
						BedwarsChristmasBoxes                            int      `json:"bedwars_christmas_boxes"`
						EightTwoDiamondResourcesCollectedBedwars         int      `json:"eight_two_diamond_resources_collected_bedwars"`
						FourThreeFallFinalDeathsBedwars                  int      `json:"four_three_fall_final_deaths_bedwars"`
						EightTwoEmeraldResourcesCollectedBedwars         int      `json:"eight_two_emerald_resources_collected_bedwars"`
						EightTwoFinalKillsBedwars                        int      `json:"eight_two_final_kills_bedwars"`
						EightTwoVoidFinalKillsBedwars                    int      `json:"eight_two_void_final_kills_bedwars"`
						FourFourProjectileFinalDeathsBedwars             int      `json:"four_four_projectile_final_deaths_bedwars"`
						ProjectileFinalDeathsBedwars                     int      `json:"projectile_final_deaths_bedwars"`
						FourFourPermanentItemsPurchasedBedwars           int      `json:"four_four_permanent_items_purchased_bedwars"`
						PermanentItemsPurchasedBedwars                   int      `json:"permanent_items_purchased_bedwars"`
						TwoFourItemsPurchasedBedwars                     int      `json:"two_four_items_purchased_bedwars"`
						TwoFourBedsLostBedwars                           int      `json:"two_four_beds_lost_bedwars"`
						TwoFourDeathsBedwars                             int      `json:"two_four_deaths_bedwars"`
						TwoFourEntityAttackDeathsBedwars                 int      `json:"two_four_entity_attack_deaths_bedwars"`
						TwoFourEntityAttackFinalDeathsBedwars            int      `json:"two_four_entity_attack_final_deaths_bedwars"`
						TwoFourEntityAttackKillsBedwars                  int      `json:"two_four_entity_attack_kills_bedwars"`
						TwoFourFinalDeathsBedwars                        int      `json:"two_four_final_deaths_bedwars"`
						TwoFourGamesPlayedBedwars                        int      `json:"two_four_games_played_bedwars"`
						TwoFourGoldResourcesCollectedBedwars             int      `json:"two_four_gold_resources_collected_bedwars"`
						TwoFourIronResourcesCollectedBedwars             int      `json:"two_four_iron_resources_collected_bedwars"`
						TwoFourKillsBedwars                              int      `json:"two_four_kills_bedwars"`
						TwoFourLossesBedwars                             int      `json:"two_four_losses_bedwars"`
						TwoFourResourcesCollectedBedwars                 int      `json:"two_four_resources_collected_bedwars"`
						EightTwoBedsBrokenBedwars                        int      `json:"eight_two_beds_broken_bedwars"`
						MagicFinalKillsBedwars                           int      `json:"magic_final_kills_bedwars"`
						MagicKillsBedwars                                int      `json:"magic_kills_bedwars"`
						TwoFourBedsBrokenBedwars                         int      `json:"two_four_beds_broken_bedwars"`
						TwoFourFallKillsBedwars                          int      `json:"two_four_fall_kills_bedwars"`
						TwoFourFinalKillsBedwars                         int      `json:"two_four_final_kills_bedwars"`
						TwoFourMagicFinalKillsBedwars                    int      `json:"two_four_magic_final_kills_bedwars"`
						TwoFourMagicKillsBedwars                         int      `json:"two_four_magic_kills_bedwars"`
						TwoFourPermanentItemsPurchasedBedwars            int      `json:"two_four_permanent_items_purchased_bedwars"`
						TwoFourVoidDeathsBedwars                         int      `json:"two_four_void_deaths_bedwars"`
						TwoFourVoidFinalKillsBedwars                     int      `json:"two_four_void_final_kills_bedwars"`
						TwoFourVoidKillsBedwars                          int      `json:"two_four_void_kills_bedwars"`
						TwoFourWinsBedwars                               int      `json:"two_four_wins_bedwars"`
						TwoFourFallDeathsBedwars                         int      `json:"two_four_fall_deaths_bedwars"`
						TwoFourFallFinalDeathsBedwars                    int      `json:"two_four_fall_final_deaths_bedwars"`
						TwoFourVoidFinalDeathsBedwars                    int      `json:"two_four_void_final_deaths_bedwars"`
						TwoFourEntityAttackFinalKillsBedwars             int      `json:"two_four_entity_attack_final_kills_bedwars"`
						TwoFourEmeraldResourcesCollectedBedwars          int      `json:"two_four_emerald_resources_collected_bedwars"`
						EightOneBedsBrokenBedwars                        int      `json:"eight_one_beds_broken_bedwars"`
						EightOneEntityAttackDeathsBedwars                int      `json:"eight_one_entity_attack_deaths_bedwars"`
						EightOneEntityAttackKillsBedwars                 int      `json:"eight_one_entity_attack_kills_bedwars"`
						EightOneKillsBedwars                             int      `json:"eight_one_kills_bedwars"`
						FourFourMagicFinalDeathsBedwars                  int      `json:"four_four_magic_final_deaths_bedwars"`
						MagicFinalDeathsBedwars                          int      `json:"magic_final_deaths_bedwars"`
						TwoFourFallFinalKillsBedwars                     int      `json:"two_four_fall_final_kills_bedwars"`
						FourFourMagicDeathsBedwars                       int      `json:"four_four_magic_deaths_bedwars"`
						MagicDeathsBedwars                               int      `json:"magic_deaths_bedwars"`
						ActiveBedDestroy                                 string   `json:"activeBedDestroy"`
						ActiveWoodType                                   string   `json:"activeWoodType"`
						EightOneFallDeathsBedwars                        int      `json:"eight_one_fall_deaths_bedwars"`
						EightOneVoidKillsBedwars                         int      `json:"eight_one_void_kills_bedwars"`
						EightOneEntityExplosionDeathsBedwars             int      `json:"eight_one_entity_explosion_deaths_bedwars"`
						EightOneFinalKillsBedwars                        int      `json:"eight_one_final_kills_bedwars"`
						EightOneVoidFinalDeathsBedwars                   int      `json:"eight_one_void_final_deaths_bedwars"`
						EightOneVoidFinalKillsBedwars                    int      `json:"eight_one_void_final_kills_bedwars"`
						EightOneDiamondResourcesCollectedBedwars         int      `json:"eight_one_diamond_resources_collected_bedwars"`
						EightOneMagicDeathsBedwars                       int      `json:"eight_one_magic_deaths_bedwars"`
						FourFourMagicKillsBedwars                        int      `json:"four_four_magic_kills_bedwars"`
						ShopSort                                         string   `json:"shop_sort"`
						ActiveVictoryDance                               string   `json:"activeVictoryDance"`
						UnderstandsResourceBank                          bool     `json:"understands_resource_bank"`
						CastleEntityAttackFinalDeathsBedwars             int      `json:"castle_entity_attack_final_deaths_bedwars"`
						CastleMagicDeathsBedwars                         int      `json:"castle_magic_deaths_bedwars"`
						CastlePermanentItemsPurchasedBedwars             int      `json:"castle_permanent_items_purchased_bedwars"`
						CastleEntityExplosionFinalDeathsBedwars          int      `json:"castle_entity_explosion_final_deaths_bedwars"`
						CastleKillsBedwars                               int      `json:"castle_kills_bedwars"`
						CastleVoidKillsBedwars                           int      `json:"castle_void_kills_bedwars"`
						EightTwoEntityAttackFinalKillsBedwars            int      `json:"eight_two_entity_attack_final_kills_bedwars"`
						EightOneFallFinalDeathsBedwars                   int      `json:"eight_one_fall_final_deaths_bedwars"`
						EightOneEmeraldResourcesCollectedBedwars         int      `json:"eight_one_emerald_resources_collected_bedwars"`
						EightOneWinsBedwars                              int      `json:"eight_one_wins_bedwars"`
						FireTickFinalDeathsBedwars                       int      `json:"fire_tick_final_deaths_bedwars"`
						FourFourFireTickFinalDeathsBedwars               int      `json:"four_four_fire_tick_final_deaths_bedwars"`
						FireTickDeathsBedwars                            int      `json:"fire_tick_deaths_bedwars"`
						FourFourFireTickDeathsBedwars                    int      `json:"four_four_fire_tick_deaths_bedwars"`
						EightTwoFallDeathsBedwars                        int      `json:"eight_two_fall_deaths_bedwars"`
						EightTwoMagicFinalDeathsBedwars                  int      `json:"eight_two_magic_final_deaths_bedwars"`
						FourFourLuckyItemsPurchasedBedwars               int      `json:"four_four_lucky_items_purchased_bedwars"`
						FourFourLuckyBedsLostBedwars                     int      `json:"four_four_lucky_beds_lost_bedwars"`
						FourFourLuckyDeathsBedwars                       int      `json:"four_four_lucky_deaths_bedwars"`
						FourFourLuckyEntityAttackDeathsBedwars           int      `json:"four_four_lucky_entity_attack_deaths_bedwars"`
						FourFourLuckyFallFinalKillsBedwars               int      `json:"four_four_lucky_fall_final_kills_bedwars"`
						FourFourLuckyFinalDeathsBedwars                  int      `json:"four_four_lucky_final_deaths_bedwars"`
						FourFourLuckyFinalKillsBedwars                   int      `json:"four_four_lucky_final_kills_bedwars"`
						FourFourLuckyGamesPlayedBedwars                  int      `json:"four_four_lucky_games_played_bedwars"`
						FourFourLuckyGoldResourcesCollectedBedwars       int      `json:"four_four_lucky_gold_resources_collected_bedwars"`
						FourFourLuckyIronResourcesCollectedBedwars       int      `json:"four_four_lucky_iron_resources_collected_bedwars"`
						FourFourLuckyLossesBedwars                       int      `json:"four_four_lucky_losses_bedwars"`
						FourFourLuckyPermanentItemsPurchasedBedwars      int      `json:"four_four_lucky_permanent_items_purchased_bedwars"`
						FourFourLuckyResourcesCollectedBedwars           int      `json:"four_four_lucky_resources_collected_bedwars"`
						FourFourLuckyVoidFinalDeathsBedwars              int      `json:"four_four_lucky_void_final_deaths_bedwars"`
						FourFourLuckyEntityAttackFinalDeathsBedwars      int      `json:"four_four_lucky_entity_attack_final_deaths_bedwars"`
						FourFourMagicFinalKillsBedwars                   int      `json:"four_four_magic_final_kills_bedwars"`
						TwoFourMagicFinalDeathsBedwars                   int      `json:"two_four_magic_final_deaths_bedwars"`
						FourFourArmedItemsPurchasedBedwars               int      `json:"four_four_armed_items_purchased_bedwars"`
						FourFourArmedDeathsBedwars                       int      `json:"four_four_armed_deaths_bedwars"`
						FourFourArmedGamesPlayedBedwars                  int      `json:"four_four_armed_games_played_bedwars"`
						FourFourArmedGoldResourcesCollectedBedwars       int      `json:"four_four_armed_gold_resources_collected_bedwars"`
						FourFourArmedIronResourcesCollectedBedwars       int      `json:"four_four_armed_iron_resources_collected_bedwars"`
						FourFourArmedLossesBedwars                       int      `json:"four_four_armed_losses_bedwars"`
						FourFourArmedMagicDeathsBedwars                  int      `json:"four_four_armed_magic_deaths_bedwars"`
						FourFourArmedResourcesCollectedBedwars           int      `json:"four_four_armed_resources_collected_bedwars"`
						FourFourArmedVoidDeathsBedwars                   int      `json:"four_four_armed_void_deaths_bedwars"`
						EntityExplosionFinalKillsBedwars                 int      `json:"entity_explosion_final_kills_bedwars"`
						FourFourEntityExplosionFinalKillsBedwars         int      `json:"four_four_entity_explosion_final_kills_bedwars"`
						EightOneEntityAttackFinalKillsBedwars            int      `json:"eight_one_entity_attack_final_kills_bedwars"`
						EightOneMagicFinalKillsBedwars                   int      `json:"eight_one_magic_final_kills_bedwars"`
						EightOneFallKillsBedwars                         int      `json:"eight_one_fall_kills_bedwars"`
						EightTwoWinsBedwars                              int      `json:"eight_two_wins_bedwars"`
						EightTwoMagicDeathsBedwars                       int      `json:"eight_two_magic_deaths_bedwars"`
						EightOneMagicFinalDeathsBedwars                  int      `json:"eight_one_magic_final_deaths_bedwars"`
						FourFourLuckyBedsBrokenBedwars                   int      `json:"four_four_lucky_beds_broken_bedwars"`
						FourFourLuckyVoidDeathsBedwars                   int      `json:"four_four_lucky_void_deaths_bedwars"`
						EightTwoFallKillsBedwars                         int      `json:"eight_two_fall_kills_bedwars"`
						EightTwoMagicKillsBedwars                        int      `json:"eight_two_magic_kills_bedwars"`
						EightTwoFallFinalDeathsBedwars                   int      `json:"eight_two_fall_final_deaths_bedwars"`
						FourFourRushItemsPurchasedBedwars                int      `json:"four_four_rush_items_purchased_bedwars"`
						FourFourRushBedsLostBedwars                      int      `json:"four_four_rush_beds_lost_bedwars"`
						FourFourRushDeathsBedwars                        int      `json:"four_four_rush_deaths_bedwars"`
						FourFourRushDiamondResourcesCollectedBedwars     int      `json:"four_four_rush_diamond_resources_collected_bedwars"`
						FourFourRushEmeraldResourcesCollectedBedwars     int      `json:"four_four_rush_emerald_resources_collected_bedwars"`
						FourFourRushEntityAttackDeathsBedwars            int      `json:"four_four_rush_entity_attack_deaths_bedwars"`
						FourFourRushEntityAttackFinalKillsBedwars        int      `json:"four_four_rush_entity_attack_final_kills_bedwars"`
						FourFourRushEntityAttackKillsBedwars             int      `json:"four_four_rush_entity_attack_kills_bedwars"`
						FourFourRushFallKillsBedwars                     int      `json:"four_four_rush_fall_kills_bedwars"`
						FourFourRushFinalKillsBedwars                    int      `json:"four_four_rush_final_kills_bedwars"`
						FourFourRushGamesPlayedBedwars                   int      `json:"four_four_rush_games_played_bedwars"`
						FourFourRushGoldResourcesCollectedBedwars        int      `json:"four_four_rush_gold_resources_collected_bedwars"`
						FourFourRushIronResourcesCollectedBedwars        int      `json:"four_four_rush_iron_resources_collected_bedwars"`
						FourFourRushKillsBedwars                         int      `json:"four_four_rush_kills_bedwars"`
						FourFourRushMagicKillsBedwars                    int      `json:"four_four_rush_magic_kills_bedwars"`
						FourFourRushPermanentItemsPurchasedBedwars       int      `json:"four_four_rush_permanent_items_purchased_bedwars"`
						FourFourRushResourcesCollectedBedwars            int      `json:"four_four_rush_resources_collected_bedwars"`
						FourFourRushVoidDeathsBedwars                    int      `json:"four_four_rush_void_deaths_bedwars"`
						FourFourRushVoidFinalKillsBedwars                int      `json:"four_four_rush_void_final_kills_bedwars"`
						FourFourRushWinsBedwars                          int      `json:"four_four_rush_wins_bedwars"`
						FourFourRushFinalDeathsBedwars                   int      `json:"four_four_rush_final_deaths_bedwars"`
						FourFourRushLossesBedwars                        int      `json:"four_four_rush_losses_bedwars"`
						FourFourRushVoidFinalDeathsBedwars               int      `json:"four_four_rush_void_final_deaths_bedwars"`
						FreeEventKeyBedwarsHalloweenBoxes2020            bool     `json:"free_event_key_bedwars_halloween_boxes_2020"`
						FourThreeMagicFinalDeathsBedwars                 int      `json:"four_three_magic_final_deaths_bedwars"`
						FourThreeFallKillsBedwars                        int      `json:"four_three_fall_kills_bedwars"`
						FourFourProjectileFinalKillsBedwars              int      `json:"four_four_projectile_final_kills_bedwars"`
						ProjectileFinalKillsBedwars                      int      `json:"projectile_final_kills_bedwars"`
						FourThreeMagicDeathsBedwars                      int      `json:"four_three_magic_deaths_bedwars"`
						FourThreeFireTickDeathsBedwars                   int      `json:"four_three_fire_tick_deaths_bedwars"`
						EightTwoEntityExplosionFinalDeathsBedwars        int      `json:"eight_two_entity_explosion_final_deaths_bedwars"`
						EightOneEntityExplosionKillsBedwars              int      `json:"eight_one_entity_explosion_kills_bedwars"`
						EightTwoMagicFinalKillsBedwars                   int      `json:"eight_two_magic_final_kills_bedwars"`
						EightTwoFallFinalKillsBedwars                    int      `json:"eight_two_fall_final_kills_bedwars"`
						EightOneMagicKillsBedwars                        int      `json:"eight_one_magic_kills_bedwars"`
						FourThreeEntityExplosionKillsBedwars             int      `json:"four_three_entity_explosion_kills_bedwars"`
						EightOneProjectileFinalDeathsBedwars             int      `json:"eight_one_projectile_final_deaths_bedwars"`
						EightOneFallFinalKillsBedwars                    int      `json:"eight_one_fall_final_kills_bedwars"`
						FourFourUltimateEntityAttackDeathsBedwars        int      `json:"four_four_ultimate_entity_attack_deaths_bedwars"`
						FourFourUltimatePermanentItemsPurchasedBedwars   int      `json:"four_four_ultimate_permanent_items_purchased_bedwars"`
						FourFourUltimateWinsBedwars                      int      `json:"four_four_ultimate_wins_bedwars"`
						FourFourUltimateFinalKillsBedwars                int      `json:"four_four_ultimate_final_kills_bedwars"`
						FourFourUltimateVoidFinalKillsBedwars            int      `json:"four_four_ultimate_void_final_kills_bedwars"`
						FourFourUltimateBedsLostBedwars                  int      `json:"four_four_ultimate_beds_lost_bedwars"`
						FourFourUltimateFinalDeathsBedwars               int      `json:"four_four_ultimate_final_deaths_bedwars"`
						FourFourUltimateVoidFinalDeathsBedwars           int      `json:"four_four_ultimate_void_final_deaths_bedwars"`
						FourFourUltimateEntityAttackKillsBedwars         int      `json:"four_four_ultimate_entity_attack_kills_bedwars"`
						FourFourUltimateKillsBedwars                     int      `json:"four_four_ultimate_kills_bedwars"`
						FourFourUltimateVoidKillsBedwars                 int      `json:"four_four_ultimate_void_kills_bedwars"`
						FourFourUltimateBedsBrokenBedwars                int      `json:"four_four_ultimate_beds_broken_bedwars"`
						FourFourUltimateEntityAttackFinalDeathsBedwars   int      `json:"four_four_ultimate_entity_attack_final_deaths_bedwars"`
						FourFourUltimateEntityAttackFinalKillsBedwars    int      `json:"four_four_ultimate_entity_attack_final_kills_bedwars"`
						FourFourUltimateDiamondResourcesCollectedBedwars int      `json:"four_four_ultimate_diamond_resources_collected_bedwars"`
						FreeEventKeyBedwarsChristmasBoxes2020            bool     `json:"free_event_key_bedwars_christmas_boxes_2020"`
						FourFourVoidlessItemsPurchasedBedwars            int      `json:"four_four_voidless_items_purchased_bedwars"`
						FourFourVoidlessBedsLostBedwars                  int      `json:"four_four_voidless_beds_lost_bedwars"`
						FourFourVoidlessEmeraldResourcesCollectedBedwars int      `json:"four_four_voidless_emerald_resources_collected_bedwars"`
						FourFourVoidlessEntityAttackFinalDeathsBedwars   int      `json:"four_four_voidless_entity_attack_final_deaths_bedwars"`
						FourFourVoidlessEntityAttackKillsBedwars         int      `json:"four_four_voidless_entity_attack_kills_bedwars"`
						FourFourVoidlessFinalDeathsBedwars               int      `json:"four_four_voidless_final_deaths_bedwars"`
						FourFourVoidlessGamesPlayedBedwars               int      `json:"four_four_voidless_games_played_bedwars"`
						FourFourVoidlessGoldResourcesCollectedBedwars    int      `json:"four_four_voidless_gold_resources_collected_bedwars"`
						FourFourVoidlessIronResourcesCollectedBedwars    int      `json:"four_four_voidless_iron_resources_collected_bedwars"`
						FourFourVoidlessKillsBedwars                     int      `json:"four_four_voidless_kills_bedwars"`
						FourFourVoidlessLossesBedwars                    int      `json:"four_four_voidless_losses_bedwars"`
						FourFourVoidlessMagicKillsBedwars                int      `json:"four_four_voidless_magic_kills_bedwars"`
						FourFourVoidlessResourcesCollectedBedwars        int      `json:"four_four_voidless_resources_collected_bedwars"`
						FourThreeFallFinalKillsBedwars                   int      `json:"four_three_fall_final_kills_bedwars"`
						FourThreeMagicFinalKillsBedwars                  int      `json:"four_three_magic_final_kills_bedwars"`
						EightOneProjectileDeathsBedwars                  int      `json:"eight_one_projectile_deaths_bedwars"`
						FireDeathsBedwars                                int      `json:"fire_deaths_bedwars"`
						FourFourFireDeathsBedwars                        int      `json:"four_four_fire_deaths_bedwars"`
						EightOneFireTickFinalDeathsBedwars               int      `json:"eight_one_fire_tick_final_deaths_bedwars"`
						FreeEventKeyBedwarsChristmasBoxes2021            bool     `json:"free_event_key_bedwars_christmas_boxes_2021"`
						FourFourUltimateMagicFinalDeathsBedwars          int      `json:"four_four_ultimate_magic_final_deaths_bedwars"`
						FourFourUltimateEmeraldResourcesCollectedBedwars int      `json:"four_four_ultimate_emerald_resources_collected_bedwars"`
						FourFourUltimateMagicFinalKillsBedwars           int      `json:"four_four_ultimate_magic_final_kills_bedwars"`
						FourFourUltimateMagicDeathsBedwars               int      `json:"four_four_ultimate_magic_deaths_bedwars"`
						FourFourUltimateMagicKillsBedwars                int      `json:"four_four_ultimate_magic_kills_bedwars"`
						CastleDiamondResourcesCollectedBedwars           int      `json:"castle_diamond_resources_collected_bedwars"`
						CastleEntityAttackKillsBedwars                   int      `json:"castle_entity_attack_kills_bedwars"`
						EightTwoEntityExplosionKillsBedwars              int      `json:"eight_two_entity_explosion_kills_bedwars"`
						EightTwoEntityExplosionDeathsBedwars             int      `json:"eight_two_entity_explosion_deaths_bedwars"`
						EightTwoLuckyItemsPurchasedBedwars               int      `json:"eight_two_lucky_items_purchased_bedwars"`
						EightTwoLuckyBedsBrokenBedwars                   int      `json:"eight_two_lucky_beds_broken_bedwars"`
						EightTwoLuckyBedsLostBedwars                     int      `json:"eight_two_lucky_beds_lost_bedwars"`
						EightTwoLuckyDeathsBedwars                       int      `json:"eight_two_lucky_deaths_bedwars"`
						EightTwoLuckyEntityAttackDeathsBedwars           int      `json:"eight_two_lucky_entity_attack_deaths_bedwars"`
						EightTwoLuckyEntityAttackFinalDeathsBedwars      int      `json:"eight_two_lucky_entity_attack_final_deaths_bedwars"`
						EightTwoLuckyEntityAttackKillsBedwars            int      `json:"eight_two_lucky_entity_attack_kills_bedwars"`
						EightTwoLuckyFinalDeathsBedwars                  int      `json:"eight_two_lucky_final_deaths_bedwars"`
						EightTwoLuckyFinalKillsBedwars                   int      `json:"eight_two_lucky_final_kills_bedwars"`
						EightTwoLuckyGamesPlayedBedwars                  int      `json:"eight_two_lucky_games_played_bedwars"`
						EightTwoLuckyGoldResourcesCollectedBedwars       int      `json:"eight_two_lucky_gold_resources_collected_bedwars"`
						EightTwoLuckyIronResourcesCollectedBedwars       int      `json:"eight_two_lucky_iron_resources_collected_bedwars"`
						EightTwoLuckyKillsBedwars                        int      `json:"eight_two_lucky_kills_bedwars"`
						EightTwoLuckyLossesBedwars                       int      `json:"eight_two_lucky_losses_bedwars"`
						EightTwoLuckyResourcesCollectedBedwars           int      `json:"eight_two_lucky_resources_collected_bedwars"`
						EightTwoLuckyVoidDeathsBedwars                   int      `json:"eight_two_lucky_void_deaths_bedwars"`
						EightTwoLuckyVoidFinalKillsBedwars               int      `json:"eight_two_lucky_void_final_kills_bedwars"`
						EightTwoLuckyVoidKillsBedwars                    int      `json:"eight_two_lucky_void_kills_bedwars"`
						EightTwoLuckyDiamondResourcesCollectedBedwars    int      `json:"eight_two_lucky_diamond_resources_collected_bedwars"`
						EightTwoLuckyEmeraldResourcesCollectedBedwars    int      `json:"eight_two_lucky_emerald_resources_collected_bedwars"`
						EightTwoLuckyFallDeathsBedwars                   int      `json:"eight_two_lucky_fall_deaths_bedwars"`
						EightTwoLuckyMagicFinalDeathsBedwars             int      `json:"eight_two_lucky_magic_final_deaths_bedwars"`
						EightTwoLuckyPermanentItemsPurchasedBedwars      int      `json:"eight_two_lucky_permanent_items_purchased_bedwars"`
						EightOneFireTickDeathsBedwars                    int      `json:"eight_one_fire_tick_deaths_bedwars"`
						EightTwoRushItemsPurchasedBedwars                int      `json:"eight_two_rush_items_purchased_bedwars"`
						EightTwoRushBedsBrokenBedwars                    int      `json:"eight_two_rush_beds_broken_bedwars"`
						EightTwoRushBedsLostBedwars                      int      `json:"eight_two_rush_beds_lost_bedwars"`
						EightTwoRushDeathsBedwars                        int      `json:"eight_two_rush_deaths_bedwars"`
						EightTwoRushDiamondResourcesCollectedBedwars     int      `json:"eight_two_rush_diamond_resources_collected_bedwars"`
						EightTwoRushEmeraldResourcesCollectedBedwars     int      `json:"eight_two_rush_emerald_resources_collected_bedwars"`
						EightTwoRushEntityAttackDeathsBedwars            int      `json:"eight_two_rush_entity_attack_deaths_bedwars"`
						EightTwoRushEntityAttackFinalDeathsBedwars       int      `json:"eight_two_rush_entity_attack_final_deaths_bedwars"`
						EightTwoRushEntityAttackFinalKillsBedwars        int      `json:"eight_two_rush_entity_attack_final_kills_bedwars"`
						EightTwoRushEntityAttackKillsBedwars             int      `json:"eight_two_rush_entity_attack_kills_bedwars"`
						EightTwoRushFinalDeathsBedwars                   int      `json:"eight_two_rush_final_deaths_bedwars"`
						EightTwoRushFinalKillsBedwars                    int      `json:"eight_two_rush_final_kills_bedwars"`
						EightTwoRushGamesPlayedBedwars                   int      `json:"eight_two_rush_games_played_bedwars"`
						EightTwoRushGoldResourcesCollectedBedwars        int      `json:"eight_two_rush_gold_resources_collected_bedwars"`
						EightTwoRushIronResourcesCollectedBedwars        int      `json:"eight_two_rush_iron_resources_collected_bedwars"`
						EightTwoRushKillsBedwars                         int      `json:"eight_two_rush_kills_bedwars"`
						EightTwoRushLossesBedwars                        int      `json:"eight_two_rush_losses_bedwars"`
						EightTwoRushPermanentItemsPurchasedBedwars       int      `json:"eight_two_rush_permanent_items_purchased_bedwars"`
						EightTwoRushResourcesCollectedBedwars            int      `json:"eight_two_rush_resources_collected_bedwars"`
						EightTwoRushVoidDeathsBedwars                    int      `json:"eight_two_rush_void_deaths_bedwars"`
						EightTwoRushVoidKillsBedwars                     int      `json:"eight_two_rush_void_kills_bedwars"`
						FourFourRushBedsBrokenBedwars                    int      `json:"four_four_rush_beds_broken_bedwars"`
						FourFourRushFireTickFinalDeathsBedwars           int      `json:"four_four_rush_fire_tick_final_deaths_bedwars"`
						FourFourRushVoidKillsBedwars                     int      `json:"four_four_rush_void_kills_bedwars"`
						TwoFourDiamondResourcesCollectedBedwars          int      `json:"two_four_diamond_resources_collected_bedwars"`
						Privategames                                     struct {
							MaxTeamUpgrades        bool   `json:"max_team_upgrades"`
							BedInstabreak          bool   `json:"bed_instabreak"`
							DisableBlockProtection bool   `json:"disable_block_protection"`
							EventTime              string `json:"event_time"`
							RespawnTime            string `json:"respawn_time"`
							OneHitOneKill          bool   `json:"one_hit_one_kill"`
							HealthBuff             string `json:"health_buff"`
							NoEmeralds             bool   `json:"no_emeralds"`
							NoDiamonds             bool   `json:"no_diamonds"`
							Speed                  string `json:"speed"`
							LowGravity             bool   `json:"low_gravity"`
						} `json:"privategames"`
						CastleEntityAttackFinalKillsBedwars int `json:"castle_entity_attack_final_kills_bedwars"`
						CastleFallDeathsBedwars             int `json:"castle_fall_deaths_bedwars"`
						CastleFinalKillsBedwars             int `json:"castle_final_kills_bedwars"`
						CastleVoidFinalKillsBedwars         int `json:"castle_void_final_kills_bedwars"`
						CastleWinsBedwars                   int `json:"castle_wins_bedwars"`
						CastleFallKillsBedwars              int `json:"castle_fall_kills_bedwars"`
						CastleFallFinalDeathsBedwars        int `json:"castle_fall_final_deaths_bedwars"`
						CastleMagicFinalDeathsBedwars       int `json:"castle_magic_final_deaths_bedwars"`
						EightTwoProjectileDeathsBedwars     int `json:"eight_two_projectile_deaths_bedwars"`
						Practice                            struct {
							Selected        string `json:"selected"`
							FireballJumping struct {
								SuccessfulAttempts int `json:"successful_attempts"`
								BlocksPlaced       int `json:"blocks_placed"`
								FailedAttempts     int `json:"failed_attempts"`
							} `json:"fireball_jumping"`
							Mlg struct {
								SuccessfulAttempts int `json:"successful_attempts"`
								FailedAttempts     int `json:"failed_attempts"`
								BlocksPlaced       int `json:"blocks_placed"`
							} `json:"mlg"`
							Records struct {
								BridgingDistance30ElevationNONEAngleSTRAIGHT      int `json:"bridging_distance_30:elevation_NONE:angle_STRAIGHT:"`
								BridgingDistance30ElevationSTAIRCASEAngleSTRAIGHT int `json:"bridging_distance_30:elevation_STAIRCASE:angle_STRAIGHT:"`
								BridgingDistance30ElevationNONEAngleDIAGONAL      int `json:"bridging_distance_30:elevation_NONE:angle_DIAGONAL:"`
								BridgingDistance30ElevationSLIGHTAngleSTRAIGHT    int `json:"bridging_distance_30:elevation_SLIGHT:angle_STRAIGHT:"`
							} `json:"records"`
							Bridging struct {
								FailedAttempts     int `json:"failed_attempts"`
								SuccessfulAttempts int `json:"successful_attempts"`
								BlocksPlaced       int `json:"blocks_placed"`
							} `json:"bridging"`
						} `json:"practice"`
						EightTwoVoidlessItemsPurchasedBedwars                   int            `json:"eight_two_voidless_items_purchased_bedwars"`
						EightTwoVoidlessBedsLostBedwars                         int            `json:"eight_two_voidless_beds_lost_bedwars"`
						EightTwoVoidlessDeathsBedwars                           int            `json:"eight_two_voidless_deaths_bedwars"`
						EightTwoVoidlessEntityAttackDeathsBedwars               int            `json:"eight_two_voidless_entity_attack_deaths_bedwars"`
						EightTwoVoidlessEntityAttackFinalDeathsBedwars          int            `json:"eight_two_voidless_entity_attack_final_deaths_bedwars"`
						EightTwoVoidlessEntityAttackKillsBedwars                int            `json:"eight_two_voidless_entity_attack_kills_bedwars"`
						EightTwoVoidlessFinalDeathsBedwars                      int            `json:"eight_two_voidless_final_deaths_bedwars"`
						EightTwoVoidlessGamesPlayedBedwars                      int            `json:"eight_two_voidless_games_played_bedwars"`
						EightTwoVoidlessGoldResourcesCollectedBedwars           int            `json:"eight_two_voidless_gold_resources_collected_bedwars"`
						EightTwoVoidlessIronResourcesCollectedBedwars           int            `json:"eight_two_voidless_iron_resources_collected_bedwars"`
						EightTwoVoidlessKillsBedwars                            int            `json:"eight_two_voidless_kills_bedwars"`
						EightTwoVoidlessResourcesCollectedBedwars               int            `json:"eight_two_voidless_resources_collected_bedwars"`
						FourFourVoidlessFallFinalDeathsBedwars                  int            `json:"four_four_voidless_fall_final_deaths_bedwars"`
						FourFourVoidlessBedsBrokenBedwars                       int            `json:"four_four_voidless_beds_broken_bedwars"`
						FourFourVoidlessDeathsBedwars                           int            `json:"four_four_voidless_deaths_bedwars"`
						FourFourVoidlessEntityAttackDeathsBedwars               int            `json:"four_four_voidless_entity_attack_deaths_bedwars"`
						FourFourVoidlessEntityAttackFinalKillsBedwars           int            `json:"four_four_voidless_entity_attack_final_kills_bedwars"`
						FourFourVoidlessFinalKillsBedwars                       int            `json:"four_four_voidless_final_kills_bedwars"`
						FourFourVoidlessPermanentItemsPurchasedBedwars          int            `json:"four_four_voidless_permanent_items_purchased_bedwars"`
						FourFourVoidlessEntityExplosionKillsBedwars             int            `json:"four_four_voidless_entity_explosion_kills_bedwars"`
						FourFourVoidlessFallFinalKillsBedwars                   int            `json:"four_four_voidless_fall_final_kills_bedwars"`
						EightOneEntityExplosionFinalDeathsBedwars               int            `json:"eight_one_entity_explosion_final_deaths_bedwars"`
						EightTwoVoidlessBedsBrokenBedwars                       int            `json:"eight_two_voidless_beds_broken_bedwars"`
						EightTwoVoidlessDiamondResourcesCollectedBedwars        int            `json:"eight_two_voidless_diamond_resources_collected_bedwars"`
						EightTwoVoidlessEmeraldResourcesCollectedBedwars        int            `json:"eight_two_voidless_emerald_resources_collected_bedwars"`
						EightTwoVoidlessEntityAttackFinalKillsBedwars           int            `json:"eight_two_voidless_entity_attack_final_kills_bedwars"`
						EightTwoVoidlessFallFinalKillsBedwars                   int            `json:"eight_two_voidless_fall_final_kills_bedwars"`
						EightTwoVoidlessFinalKillsBedwars                       int            `json:"eight_two_voidless_final_kills_bedwars"`
						EightTwoVoidlessLossesBedwars                           int            `json:"eight_two_voidless_losses_bedwars"`
						EightTwoVoidlessPermanentItemsPurchasedBedwars          int            `json:"eight_two_voidless_permanent_items_purchased_bedwars"`
						EightTwoVoidlessFallDeathsBedwars                       int            `json:"eight_two_voidless_fall_deaths_bedwars"`
						EightTwoVoidlessWinsBedwars                             int            `json:"eight_two_voidless_wins_bedwars"`
						EightTwoVoidlessFallKillsBedwars                        int            `json:"eight_two_voidless_fall_kills_bedwars"`
						EightTwoVoidlessMagicDeathsBedwars                      int            `json:"eight_two_voidless_magic_deaths_bedwars"`
						EightTwoVoidlessFireTickKillsBedwars                    int            `json:"eight_two_voidless_fire_tick_kills_bedwars"`
						EightTwoVoidlessFallFinalDeathsBedwars                  int            `json:"eight_two_voidless_fall_final_deaths_bedwars"`
						EightTwoFireKillsBedwars                                int            `json:"eight_two_fire_kills_bedwars"`
						FireKillsBedwars                                        int            `json:"fire_kills_bedwars"`
						EightTwoLuckyMagicDeathsBedwars                         int            `json:"eight_two_lucky_magic_deaths_bedwars"`
						FourFourRushMagicFinalDeathsBedwars                     int            `json:"four_four_rush_magic_final_deaths_bedwars"`
						FourFourRushEntityAttackFinalDeathsBedwars              int            `json:"four_four_rush_entity_attack_final_deaths_bedwars"`
						FourFourRushFallFinalKillsBedwars                       int            `json:"four_four_rush_fall_final_kills_bedwars"`
						FourFourRushFallDeathsBedwars                           int            `json:"four_four_rush_fall_deaths_bedwars"`
						EightTwoFireTickFinalKillsBedwars                       int            `json:"eight_two_fire_tick_final_kills_bedwars"`
						FireTickFinalKillsBedwars                               int            `json:"fire_tick_final_kills_bedwars"`
						FourThreeEntityExplosionFinalDeathsBedwars              int            `json:"four_three_entity_explosion_final_deaths_bedwars"`
						FreeEventKeyBedwarsEasterBoxes2021                      bool           `json:"free_event_key_bedwars_easter_boxes_2021"`
						EightTwoEntityExplosionFinalKillsBedwars                int            `json:"eight_two_entity_explosion_final_kills_bedwars"`
						EightTwoFireTickKillsBedwars                            int            `json:"eight_two_fire_tick_kills_bedwars"`
						FireTickKillsBedwars                                    int            `json:"fire_tick_kills_bedwars"`
						EightOneFireTickFinalKillsBedwars                       int            `json:"eight_one_fire_tick_final_kills_bedwars"`
						EightTwoLuckyVoidFinalDeathsBedwars                     int            `json:"eight_two_lucky_void_final_deaths_bedwars"`
						EightTwoFireTickDeathsBedwars                           int            `json:"eight_two_fire_tick_deaths_bedwars"`
						FourFourVoidlessWinsBedwars                             int            `json:"four_four_voidless_wins_bedwars"`
						FourFourVoidlessFallDeathsBedwars                       int            `json:"four_four_voidless_fall_deaths_bedwars"`
						FourFourVoidlessFallKillsBedwars                        int            `json:"four_four_voidless_fall_kills_bedwars"`
						FourFourVoidlessVoidFinalKillsBedwars                   int            `json:"four_four_voidless_void_final_kills_bedwars"`
						FourFourArmedEntityAttackKillsBedwars                   int            `json:"four_four_armed_entity_attack_kills_bedwars"`
						FourFourArmedFallDeathsBedwars                          int            `json:"four_four_armed_fall_deaths_bedwars"`
						FourFourArmedKillsBedwars                               int            `json:"four_four_armed_kills_bedwars"`
						FourFourArmedPermanentItemsPurchasedBedwars             int            `json:"four_four_armed_permanent_items_purchased_bedwars"`
						FourFourArmedProjectileDeathsBedwars                    int            `json:"four_four_armed_projectile_deaths_bedwars"`
						FourFourArmedProjectileKillsBedwars                     int            `json:"four_four_armed_projectile_kills_bedwars"`
						FourFourArmedVoidKillsBedwars                           int            `json:"four_four_armed_void_kills_bedwars"`
						FourFourArmedWinsBedwars                                int            `json:"four_four_armed_wins_bedwars"`
						FourFourArmedBedsBrokenBedwars                          int            `json:"four_four_armed_beds_broken_bedwars"`
						FourFourArmedBedsLostBedwars                            int            `json:"four_four_armed_beds_lost_bedwars"`
						FourFourArmedEmeraldResourcesCollectedBedwars           int            `json:"four_four_armed_emerald_resources_collected_bedwars"`
						FourFourArmedEntityAttackDeathsBedwars                  int            `json:"four_four_armed_entity_attack_deaths_bedwars"`
						FourFourArmedEntityAttackFinalKillsBedwars              int            `json:"four_four_armed_entity_attack_final_kills_bedwars"`
						FourFourArmedFinalDeathsBedwars                         int            `json:"four_four_armed_final_deaths_bedwars"`
						FourFourArmedFinalKillsBedwars                          int            `json:"four_four_armed_final_kills_bedwars"`
						FourFourArmedVoidFinalDeathsBedwars                     int            `json:"four_four_armed_void_final_deaths_bedwars"`
						FourFourLuckyEntityAttackFinalKillsBedwars              int            `json:"four_four_lucky_entity_attack_final_kills_bedwars"`
						FourFourLuckyVoidFinalKillsBedwars                      int            `json:"four_four_lucky_void_final_kills_bedwars"`
						FourFourLuckyWinsBedwars                                int            `json:"four_four_lucky_wins_bedwars"`
						FourFourLuckyEmeraldResourcesCollectedBedwars           int            `json:"four_four_lucky_emerald_resources_collected_bedwars"`
						FourFourLuckyKillsBedwars                               int            `json:"four_four_lucky_kills_bedwars"`
						FourFourLuckyMagicFinalKillsBedwars                     int            `json:"four_four_lucky_magic_final_kills_bedwars"`
						FourFourLuckyVoidKillsBedwars                           int            `json:"four_four_lucky_void_kills_bedwars"`
						FourThreeProjectileFinalKillsBedwars                    int            `json:"four_three_projectile_final_kills_bedwars"`
						EightTwoUltimateItemsPurchasedBedwars                   int            `json:"eight_two_ultimate_items_purchased_bedwars"`
						EightTwoUltimateBedsBrokenBedwars                       int            `json:"eight_two_ultimate_beds_broken_bedwars"`
						EightTwoUltimateBedsLostBedwars                         int            `json:"eight_two_ultimate_beds_lost_bedwars"`
						EightTwoUltimateDeathsBedwars                           int            `json:"eight_two_ultimate_deaths_bedwars"`
						EightTwoUltimateDiamondResourcesCollectedBedwars        int            `json:"eight_two_ultimate_diamond_resources_collected_bedwars"`
						EightTwoUltimateEmeraldResourcesCollectedBedwars        int            `json:"eight_two_ultimate_emerald_resources_collected_bedwars"`
						EightTwoUltimateEntityAttackDeathsBedwars               int            `json:"eight_two_ultimate_entity_attack_deaths_bedwars"`
						EightTwoUltimateFinalDeathsBedwars                      int            `json:"eight_two_ultimate_final_deaths_bedwars"`
						EightTwoUltimateFinalKillsBedwars                       int            `json:"eight_two_ultimate_final_kills_bedwars"`
						EightTwoUltimateGamesPlayedBedwars                      int            `json:"eight_two_ultimate_games_played_bedwars"`
						EightTwoUltimateGoldResourcesCollectedBedwars           int            `json:"eight_two_ultimate_gold_resources_collected_bedwars"`
						EightTwoUltimateIronResourcesCollectedBedwars           int            `json:"eight_two_ultimate_iron_resources_collected_bedwars"`
						EightTwoUltimateKillsBedwars                            int            `json:"eight_two_ultimate_kills_bedwars"`
						EightTwoUltimateLossesBedwars                           int            `json:"eight_two_ultimate_losses_bedwars"`
						EightTwoUltimateMagicFinalDeathsBedwars                 int            `json:"eight_two_ultimate_magic_final_deaths_bedwars"`
						EightTwoUltimatePermanentItemsPurchasedBedwars          int            `json:"eight_two_ultimate_permanent_items_purchased_bedwars"`
						EightTwoUltimateResourcesCollectedBedwars               int            `json:"eight_two_ultimate_resources_collected_bedwars"`
						EightTwoUltimateVoidDeathsBedwars                       int            `json:"eight_two_ultimate_void_deaths_bedwars"`
						EightTwoUltimateVoidFinalKillsBedwars                   int            `json:"eight_two_ultimate_void_final_kills_bedwars"`
						EightTwoUltimateVoidKillsBedwars                        int            `json:"eight_two_ultimate_void_kills_bedwars"`
						EightTwoUltimateEntityAttackFinalKillsBedwars           int            `json:"eight_two_ultimate_entity_attack_final_kills_bedwars"`
						EightTwoUltimateWinsBedwars                             int            `json:"eight_two_ultimate_wins_bedwars"`
						EightTwoUltimateEntityAttackFinalDeathsBedwars          int            `json:"eight_two_ultimate_entity_attack_final_deaths_bedwars"`
						EightTwoUltimateEntityAttackKillsBedwars                int            `json:"eight_two_ultimate_entity_attack_kills_bedwars"`
						EightTwoUltimateVoidFinalDeathsBedwars                  int            `json:"eight_two_ultimate_void_final_deaths_bedwars"`
						EightTwoUltimateMagicFinalKillsBedwars                  int            `json:"eight_two_ultimate_magic_final_kills_bedwars"`
						EightTwoUltimateMagicDeathsBedwars                      int            `json:"eight_two_ultimate_magic_deaths_bedwars"`
						CastleBedsBrokenBedwars                                 int            `json:"castle_beds_broken_bedwars"`
						CastleEmeraldResourcesCollectedBedwars                  int            `json:"castle_emerald_resources_collected_bedwars"`
						CastleMagicFinalKillsBedwars                            int            `json:"castle_magic_final_kills_bedwars"`
						CastleFallFinalKillsBedwars                             int            `json:"castle_fall_final_kills_bedwars"`
						ShopSortEnableOwnedFirst                                bool           `json:"shop_sort_enable_owned_first"`
						EightOneFireTickKillsBedwars                            int            `json:"eight_one_fire_tick_kills_bedwars"`
						FourFourVoidlessDiamondResourcesCollectedBedwars        int            `json:"four_four_voidless_diamond_resources_collected_bedwars"`
						FourFourVoidlessMagicFinalKillsBedwars                  int            `json:"four_four_voidless_magic_final_kills_bedwars"`
						EightTwoFireTickFinalDeathsBedwars                      int            `json:"eight_two_fire_tick_final_deaths_bedwars"`
						FourFourLuckyFireTickKillsBedwars                       int            `json:"four_four_lucky_fire_tick_kills_bedwars"`
						FourFourLuckyMagicKillsBedwars                          int            `json:"four_four_lucky_magic_kills_bedwars"`
						FourFourSuffocationFinalDeathsBedwars                   int            `json:"four_four_suffocation_final_deaths_bedwars"`
						SuffocationFinalDeathsBedwars                           int            `json:"suffocation_final_deaths_bedwars"`
						FourThreeFireTickFinalKillsBedwars                      int            `json:"four_three_fire_tick_final_kills_bedwars"`
						EightTwoSuffocationDeathsBedwars                        int            `json:"eight_two_suffocation_deaths_bedwars"`
						SuffocationDeathsBedwars                                int            `json:"suffocation_deaths_bedwars"`
						FourThreeMagicKillsBedwars                              int            `json:"four_three_magic_kills_bedwars"`
						FourThreeEntityExplosionDeathsBedwars                   int            `json:"four_three_entity_explosion_deaths_bedwars"`
						FourFourVoidlessMagicDeathsBedwars                      int            `json:"four_four_voidless_magic_deaths_bedwars"`
						FreeEventKeyBedwarsHalloweenBoxes2021                   bool           `json:"free_event_key_bedwars_halloween_boxes_2021"`
						SelectedChallengeType                                   string         `json:"selected_challenge_type"`
						FourFourUnderworldItemsPurchasedBedwars                 int            `json:"four_four_underworld_items_purchased_bedwars"`
						FourFourUnderworldBedsBrokenBedwars                     int            `json:"four_four_underworld_beds_broken_bedwars"`
						FourFourUnderworldBedsLostBedwars                       int            `json:"four_four_underworld_beds_lost_bedwars"`
						FourFourUnderworldDeathsBedwars                         int            `json:"four_four_underworld_deaths_bedwars"`
						FourFourUnderworldDiamondResourcesCollectedBedwars      int            `json:"four_four_underworld_diamond_resources_collected_bedwars"`
						FourFourUnderworldEmeraldResourcesCollectedBedwars      int            `json:"four_four_underworld_emerald_resources_collected_bedwars"`
						FourFourUnderworldEntityAttackFinalKillsBedwars         int            `json:"four_four_underworld_entity_attack_final_kills_bedwars"`
						FourFourUnderworldFinalKillsBedwars                     int            `json:"four_four_underworld_final_kills_bedwars"`
						FourFourUnderworldGamesPlayedBedwars                    int            `json:"four_four_underworld_games_played_bedwars"`
						FourFourUnderworldGoldResourcesCollectedBedwars         int            `json:"four_four_underworld_gold_resources_collected_bedwars"`
						FourFourUnderworldIronResourcesCollectedBedwars         int            `json:"four_four_underworld_iron_resources_collected_bedwars"`
						FourFourUnderworldKillsBedwars                          int            `json:"four_four_underworld_kills_bedwars"`
						FourFourUnderworldPermanentItemsPurchasedBedwars        int            `json:"four_four_underworld_permanent_items_purchased_bedwars"`
						FourFourUnderworldResourcesCollectedBedwars             int            `json:"four_four_underworld_resources_collected_bedwars"`
						FourFourUnderworldVoidDeathsBedwars                     int            `json:"four_four_underworld_void_deaths_bedwars"`
						FourFourUnderworldVoidFinalKillsBedwars                 int            `json:"four_four_underworld_void_final_kills_bedwars"`
						FourFourUnderworldVoidKillsBedwars                      int            `json:"four_four_underworld_void_kills_bedwars"`
						FourFourUnderworldWinsBedwars                           int            `json:"four_four_underworld_wins_bedwars"`
						FourFourUnderworldEntityAttackDeathsBedwars             int            `json:"four_four_underworld_entity_attack_deaths_bedwars"`
						FourFourUnderworldEntityAttackFinalDeathsBedwars        int            `json:"four_four_underworld_entity_attack_final_deaths_bedwars"`
						FourFourUnderworldEntityAttackKillsBedwars              int            `json:"four_four_underworld_entity_attack_kills_bedwars"`
						FourFourUnderworldFinalDeathsBedwars                    int            `json:"four_four_underworld_final_deaths_bedwars"`
						FourFourUnderworldLossesBedwars                         int            `json:"four_four_underworld_losses_bedwars"`
						FourFourUnderworldMagicFinalKillsBedwars                int            `json:"four_four_underworld_magic_final_kills_bedwars"`
						FourFourUnderworldFallDeathsBedwars                     int            `json:"four_four_underworld_fall_deaths_bedwars"`
						TotalChallengesCompleted                                int            `json:"total_challenges_completed"`
						BwChallengeNoTeamUpgrades                               int            `json:"bw_challenge_no_team_upgrades"`
						BwUniqueChallengesCompleted                             int            `json:"bw_unique_challenges_completed"`
						BwChallengeNoUtilities                                  int            `json:"bw_challenge_no_utilities"`
						BwChallengeSelfish                                      int            `json:"bw_challenge_selfish"`
						BwChallengeSlowGenerator                                int            `json:"bw_challenge_slow_generator"`
						BwChallengeAssassin                                     int            `json:"bw_challenge_assassin"`
						BwChallengeResetArmor                                   int            `json:"bw_challenge_reset_armor"`
						BwChallengeInvisibleShop                                int            `json:"bw_challenge_invisible_shop"`
						BwChallengeCollector                                    int            `json:"bw_challenge_collector"`
						BwChallengeWoodworker                                   int            `json:"bw_challenge_woodworker"`
						BwChallengeSponge                                       int            `json:"bw_challenge_sponge"`
						BwChallengeToxicRain                                    int            `json:"bw_challenge_toxic_rain"`
						BwChallengeDefuser                                      int            `json:"bw_challenge_defuser"`
						BwChallengeMiningFatigue                                int            `json:"bw_challenge_mining_fatigue"`
						BwChallengeNoHealing                                    int            `json:"bw_challenge_no_healing"`
						BwChallengeHotbar                                       int            `json:"bw_challenge_hotbar"`
						EightOneEntityExplosionFinalKillsBedwars                int            `json:"eight_one_entity_explosion_final_kills_bedwars"`
						TwoFourMagicDeathsBedwars                               int            `json:"two_four_magic_deaths_bedwars"`
						TwoFourEntityExplosionDeathsBedwars                     int            `json:"two_four_entity_explosion_deaths_bedwars"`
						TwoFourEntityExplosionKillsBedwars                      int            `json:"two_four_entity_explosion_kills_bedwars"`
						TwoFourEntityExplosionFinalKillsBedwars                 int            `json:"two_four_entity_explosion_final_kills_bedwars"`
						EightOneProjectileFinalKillsBedwars                     int            `json:"eight_one_projectile_final_kills_bedwars"`
						Challenges                                              map[string]int `json:"challenges"`
						FourFourSuffocationDeathsBedwars                        int            `json:"four_four_suffocation_deaths_bedwars"`
						FourFourVoidlessEntityExplosionFinalKillsBedwars        int            `json:"four_four_voidless_entity_explosion_final_kills_bedwars"`
						FourFourVoidlessFireTickFinalDeathsBedwars              int            `json:"four_four_voidless_fire_tick_final_deaths_bedwars"`
						FourFourVoidlessMagicFinalDeathsBedwars                 int            `json:"four_four_voidless_magic_final_deaths_bedwars"`
						FourFourLuckyDiamondResourcesCollectedBedwars           int            `json:"four_four_lucky_diamond_resources_collected_bedwars"`
						FourFourLuckyEntityAttackKillsBedwars                   int            `json:"four_four_lucky_entity_attack_kills_bedwars"`
						FourFourLuckyFireTickDeathsBedwars                      int            `json:"four_four_lucky_fire_tick_deaths_bedwars"`
						FourFourLuckyEntityExplosionFinalDeathsBedwars          int            `json:"four_four_lucky_entity_explosion_final_deaths_bedwars"`
						EightTwoLuckyEntityAttackFinalKillsBedwars              int            `json:"eight_two_lucky_entity_attack_final_kills_bedwars"`
						EightTwoLuckyFireTickDeathsBedwars                      int            `json:"eight_two_lucky_fire_tick_deaths_bedwars"`
						EightTwoLuckyWinsBedwars                                int            `json:"eight_two_lucky_wins_bedwars"`
						TourneyBedwarsEightTwo0ItemsPurchasedBedwars            int            `json:"tourney_bedwars_eight_two_0_items_purchased_bedwars"`
						TourneyBedwarsEightTwo0BedsBrokenBedwars                int            `json:"tourney_bedwars_eight_two_0_beds_broken_bedwars"`
						TourneyBedwarsEightTwo0BedsLostBedwars                  int            `json:"tourney_bedwars_eight_two_0_beds_lost_bedwars"`
						TourneyBedwarsEightTwo0DiamondResourcesCollectedBedwars int            `json:"tourney_bedwars_eight_two_0_diamond_resources_collected_bedwars"`
						TourneyBedwarsEightTwo0EmeraldResourcesCollectedBedwars int            `json:"tourney_bedwars_eight_two_0_emerald_resources_collected_bedwars"`
						TourneyBedwarsEightTwo0EntityAttackFinalKillsBedwars    int            `json:"tourney_bedwars_eight_two_0_entity_attack_final_kills_bedwars"`
						TourneyBedwarsEightTwo0FinalKillsBedwars                int            `json:"tourney_bedwars_eight_two_0_final_kills_bedwars"`
						TourneyBedwarsEightTwo0GamesPlayedBedwars               int            `json:"tourney_bedwars_eight_two_0_games_played_bedwars"`
						TourneyBedwarsEightTwo0GoldResourcesCollectedBedwars    int            `json:"tourney_bedwars_eight_two_0_gold_resources_collected_bedwars"`
						TourneyBedwarsEightTwo0IronResourcesCollectedBedwars    int            `json:"tourney_bedwars_eight_two_0_iron_resources_collected_bedwars"`
						TourneyBedwarsEightTwo0KillsBedwars                     int            `json:"tourney_bedwars_eight_two_0_kills_bedwars"`
						TourneyBedwarsEightTwo0PermanentItemsPurchasedBedwars   int            `json:"tourney_bedwars_eight_two_0_permanent_items_purchased_bedwars"`
						TourneyBedwarsEightTwo0ResourcesCollectedBedwars        int            `json:"tourney_bedwars_eight_two_0_resources_collected_bedwars"`
						TourneyBedwarsEightTwo0VoidFinalKillsBedwars            int            `json:"tourney_bedwars_eight_two_0_void_final_kills_bedwars"`
						TourneyBedwarsEightTwo0VoidKillsBedwars                 int            `json:"tourney_bedwars_eight_two_0_void_kills_bedwars"`
						TourneyBedwarsEightTwo0WinsBedwars                      int            `json:"tourney_bedwars_eight_two_0_wins_bedwars"`
						TourneyBedwarsEightTwo0DeathsBedwars                    int            `json:"tourney_bedwars_eight_two_0_deaths_bedwars"`
						TourneyBedwarsEightTwo0EntityAttackDeathsBedwars        int            `json:"tourney_bedwars_eight_two_0_entity_attack_deaths_bedwars"`
						TourneyBedwarsEightTwo0EntityAttackFinalDeathsBedwars   int            `json:"tourney_bedwars_eight_two_0_entity_attack_final_deaths_bedwars"`
						TourneyBedwarsEightTwo0EntityAttackKillsBedwars         int            `json:"tourney_bedwars_eight_two_0_entity_attack_kills_bedwars"`
						TourneyBedwarsEightTwo0FinalDeathsBedwars               int            `json:"tourney_bedwars_eight_two_0_final_deaths_bedwars"`
						TourneyBedwarsEightTwo0LossesBedwars                    int            `json:"tourney_bedwars_eight_two_0_losses_bedwars"`
						TourneyBedwarsEightTwo0FallFinalDeathsBedwars           int            `json:"tourney_bedwars_eight_two_0_fall_final_deaths_bedwars"`
						TourneyBedwarsEightTwo0VoidDeathsBedwars                int            `json:"tourney_bedwars_eight_two_0_void_deaths_bedwars"`
						TourneyBedwarsEightTwo0FallKillsBedwars                 int            `json:"tourney_bedwars_eight_two_0_fall_kills_bedwars"`
						TourneyBedwarsEightTwo0VoidFinalDeathsBedwars           int            `json:"tourney_bedwars_eight_two_0_void_final_deaths_bedwars"`
						TourneyBedwarsEightTwo0FallDeathsBedwars                int            `json:"tourney_bedwars_eight_two_0_fall_deaths_bedwars"`
						TourneyBedwarsEightTwo0MagicFinalKillsBedwars           int            `json:"tourney_bedwars_eight_two_0_magic_final_kills_bedwars"`
						FreeEventKeyBedwarsEasterBoxes2022                      bool           `json:"free_event_key_bedwars_easter_boxes_2022"`
						FourFourLuckyFallDeathsBedwars                          int            `json:"four_four_lucky_fall_deaths_bedwars"`
						EightTwoProjectileFinalKillsBedwars                     int            `json:"eight_two_projectile_final_kills_bedwars"`
						FourThreeFireTickKillsBedwars                           int            `json:"four_three_fire_tick_kills_bedwars"`
						EightTwoProjectileKillsBedwars                          int            `json:"eight_two_projectile_kills_bedwars"`
						FourFourFireTickFinalKillsBedwars                       int            `json:"four_four_fire_tick_final_kills_bedwars"`
						FreeEventKeyBedwarsHalloweenBoxes2022                   bool           `json:"free_event_key_bedwars_halloween_boxes_2022"`
						FreeEventKeyBedwarsChristmasBoxes2022                   bool           `json:"free_event_key_bedwars_christmas_boxes_2022"`
						LeaderboardSettings                                     struct {
							ResetType string `json:"resetType"`
							Mode      string `json:"mode"`
						} `json:"leaderboardSettings"`
						FourThreeEntityExplosionFinalKillsBedwars         int  `json:"four_three_entity_explosion_final_kills_bedwars"`
						EightTwoLuckyFallFinalDeathsBedwars               int  `json:"eight_two_lucky_fall_final_deaths_bedwars"`
						EightTwoLuckyFireTickKillsBedwars                 int  `json:"eight_two_lucky_fire_tick_kills_bedwars"`
						EightTwoLuckyFallKillsBedwars                     int  `json:"eight_two_lucky_fall_kills_bedwars"`
						EightTwoLuckyFireTickFinalKillsBedwars            int  `json:"eight_two_lucky_fire_tick_final_kills_bedwars"`
						EightTwoLuckyFireTickFinalDeathsBedwars           int  `json:"eight_two_lucky_fire_tick_final_deaths_bedwars"`
						EightTwoLuckyBedResourcesCollectedBedwars         int  `json:"eight_two_lucky_bed_resources_collected_bedwars"`
						EightTwoLuckyProjectileDeathsBedwars              int  `json:"eight_two_lucky_projectile_deaths_bedwars"`
						EightTwoLuckyEntityExplosionKillsBedwars          int  `json:"eight_two_lucky_entity_explosion_kills_bedwars"`
						EightTwoLuckyMagicFinalKillsBedwars               int  `json:"eight_two_lucky_magic_final_kills_bedwars"`
						EightOneProjectileKillsBedwars                    int  `json:"eight_one_projectile_kills_bedwars"`
						FourFourLuckyProjectileDeathsBedwars              int  `json:"four_four_lucky_projectile_deaths_bedwars"`
						FourFourLuckyMagicDeathsBedwars                   int  `json:"four_four_lucky_magic_deaths_bedwars"`
						FourFourUltimateEntityExplosionFinalKillsBedwars  int  `json:"four_four_ultimate_entity_explosion_final_kills_bedwars"`
						CastleFireTickDeathsBedwars                       int  `json:"castle_fire_tick_deaths_bedwars"`
						EightTwoUltimateFireTickDeathsBedwars             int  `json:"eight_two_ultimate_fire_tick_deaths_bedwars"`
						EightTwoUltimateEntityExplosionFinalDeathsBedwars int  `json:"eight_two_ultimate_entity_explosion_final_deaths_bedwars"`
						FreeEventKeyBedwarsHalloweenBoxes2023             bool `json:"free_event_key_bedwars_halloween_boxes_2023"`
						Slumber                                           struct {
							Quest struct {
								Started struct {
									NpcReceptionStart       bool `json:"npc_reception_start"`
									NpcLadySaichi           bool `json:"npc_lady_saichi"`
									NpcGeneralDaku          bool `json:"npc_general_daku"`
									NpcJohnPireso           bool `json:"npc_john_pireso"`
									PhaseTwoAsc             bool `json:"phase_two_asc"`
									NpcKingFlut             bool `json:"npc_king_flut"`
									NpcHammer               bool `json:"npc_hammer"`
									NpcOasis                bool `json:"npc_oasis"`
									PhaseThreeAsc           bool `json:"phase_three_asc"`
									NpcBucky                bool `json:"npc_bucky"`
									NpcBlacksmith           bool `json:"npc_blacksmith"`
									NpcBlacksmithApprentice bool `json:"npc_blacksmith_apprentice"`
									NpcLaundry              bool `json:"npc_laundry"`
								} `json:"started"`
								LastStarted struct {
									NpcReceptionStart       int64 `json:"npc_reception_start"`
									NpcLadySaichi           int64 `json:"npc_lady_saichi"`
									NpcGeneralDaku          int64 `json:"npc_general_daku"`
									NpcJohnPireso           int64 `json:"npc_john_pireso"`
									PhaseTwoAsc             int64 `json:"phase_two_asc"`
									NpcKingFlut             int64 `json:"npc_king_flut"`
									NpcHammer               int64 `json:"npc_hammer"`
									NpcOasis                int64 `json:"npc_oasis"`
									PhaseThreeAsc           int64 `json:"phase_three_asc"`
									NpcBucky                int64 `json:"npc_bucky"`
									NpcBlacksmith           int64 `json:"npc_blacksmith"`
									NpcBlacksmithApprentice int64 `json:"npc_blacksmith_apprentice"`
									NpcLaundry              int64 `json:"npc_laundry"`
								} `json:"lastStarted"`
								GamblerGeorge struct {
									WonLastGame    bool `json:"won_last_game"`
									GambleGamesWon int  `json:"gamble_games_won"`
								} `json:"gambler_george"`
								Npc struct {
									Talk struct {
										DoorManNpc             bool `json:"DoorManNpc"`
										HostessKatrinaNpc      bool `json:"HostessKatrinaNpc"`
										FredericFerntonNpc     bool `json:"FredericFerntonNpc"`
										HotelReceptionistNpc   bool `json:"HotelReceptionistNpc"`
										LadySaichiNpc          bool `json:"LadySaichiNpc"`
										GeneralDakuNpc         bool `json:"GeneralDakuNpc"`
										JohnIndigosNpc         bool `json:"JohnIndigosNpc"`
										TicketMachineNpc       bool `json:"TicketMachineNpc"`
										KingFlutNpc            bool `json:"KingFlutNpc"`
										HammerNpc              bool `json:"HammerNpc"`
										OasisSpiritNpc         bool `json:"OasisSpiritNpc"`
										JohnIndigosPhaseTwoNpc bool `json:"JohnIndigosPhaseTwoNpc"`
										ChefGarryJamseyNpc     bool `json:"ChefGarryJamseyNpc"`
										ChefBuckyNpc           bool `json:"ChefBuckyNpc"`
										BlackSmithNpc          bool `json:"BlackSmithNpc"`
										BlackSmithRobertoNpc   bool `json:"BlackSmithRobertoNpc"`
										LaundryGuyNpc          bool `json:"LaundryGuyNpc"`
									} `json:"talk"`
								} `json:"npc"`
								LastCompleted struct {
									NpcReceptionStart       int64 `json:"npc_reception_start"`
									NpcLadySaichi           int64 `json:"npc_lady_saichi"`
									NpcJohnPireso           int64 `json:"npc_john_pireso"`
									NpcGeneralDaku          int64 `json:"npc_general_daku"`
									PhaseTwoAsc             int64 `json:"phase_two_asc"`
									NpcHammer               int64 `json:"npc_hammer"`
									NpcBucky                int64 `json:"npc_bucky"`
									PhaseThreeAsc           int64 `json:"phase_three_asc"`
									NpcBlacksmithApprentice int64 `json:"npc_blacksmith_apprentice"`
									NpcKingFlut             int64 `json:"npc_king_flut"`
									NpcLaundry              int64 `json:"npc_laundry"`
								} `json:"lastCompleted"`
								Objective struct {
									ReceptionistIntroduction        bool `json:"receptionist_introduction"`
									LadySaichiMattress              bool `json:"lady_saichi_mattress"`
									JohnPiresoMap                   bool `json:"john_pireso_map"`
									GeneralDakuTea                  bool `json:"general_daku_tea"`
									PhaseTwoRecp                    bool `json:"phase_two_recp"`
									HammerCoins                     bool `json:"hammer_coins"`
									BuckySkyTeaLeaves               bool `json:"bucky_sky_tea_leaves"`
									BuckyFragments                  bool `json:"bucky_fragments"`
									BuckySkyTeaLeavesRepeat         bool `json:"bucky_sky_tea_leaves_repeat"`
									BuckyFragmentsRepeat            bool `json:"bucky_fragments_repeat"`
									KingFlutPillow                  bool `json:"king_flut_pillow"`
									PhaseThreeRecp                  bool `json:"phase_three_recp"`
									BlacksmithMold                  bool `json:"blacksmith_mold"`
									BlacksmithApprenticeIron        bool `json:"blacksmith_apprentice_iron"`
									BlacksmithApprenticeCoins       bool `json:"blacksmith_apprentice_coins"`
									KingFlutAmulet                  bool `json:"king_flut_amulet"`
									BlacksmithApprenticeIronRepeat  bool `json:"blacksmith_apprentice_iron_repeat"`
									BlacksmithApprenticeCoinsRepeat bool `json:"blacksmith_apprentice_coins_repeat"`
									BlacksmithIronBars              bool `json:"blacksmith_iron_bars"`
									BlacksmithAmulet                bool `json:"blacksmith_amulet"`
									LaundryManagerSheets            bool `json:"laundry_manager_sheets"`
									LaundryManagerSheetsRepeat      bool `json:"laundry_manager_sheets_repeat"`
								} `json:"objective"`
								Completed struct {
									NpcReceptionStart       bool `json:"npc_reception_start"`
									NpcLadySaichi           bool `json:"npc_lady_saichi"`
									NpcJohnPireso           bool `json:"npc_john_pireso"`
									NpcGeneralDaku          bool `json:"npc_general_daku"`
									PhaseTwoAsc             bool `json:"phase_two_asc"`
									NpcHammer               bool `json:"npc_hammer"`
									NpcBucky                bool `json:"npc_bucky"`
									PhaseThreeAsc           bool `json:"phase_three_asc"`
									NpcBlacksmithApprentice bool `json:"npc_blacksmith_apprentice"`
									NpcKingFlut             bool `json:"npc_king_flut"`
									NpcLaundry              bool `json:"npc_laundry"`
								} `json:"completed"`
								Item struct {
									SlumberItemBedSheets       int `json:"slumber_item_bed_sheets"`
									SlumberItemPerfume         int `json:"slumber_item_perfume"`
									SlumberItemEnderDust       int `json:"slumber_item_ender_dust"`
									SlumberItemIndigosMap      int `json:"slumber_item_indigos_map"`
									SlumberItemTrustyRope      int `json:"slumber_item_trusty_rope"`
									SlumberItemImperialLeather int `json:"slumber_item_imperial_leather"`
									SlumberItemComfyPillow     int `json:"slumber_item_comfy_pillow"`
									SlumberItemSilverCoins     int `json:"slumber_item_silver_coins"`
									SlumberItemSoul            int `json:"slumber_item_soul"`
									SlumberItemWeaponMold      int `json:"slumber_item_weapon_mold"`
									SlumberItemIronNugget      int `json:"slumber_item_iron_nugget"`
									SlumberItemMissingAmulet   int `json:"slumber_item_missing_amulet"`
									SlumberItemAmulet          int `json:"slumber_item_amulet"`
									SlumberItemGoldenTicket    int `json:"slumber_item_golden_ticket"`
								} `json:"item"`
							} `json:"quest"`
							BagType               string          `json:"bag_type"`
							TotalTicketsEarned    int             `json:"total_tickets_earned"`
							Tickets               int             `json:"tickets"`
							TicketsGivenDoorman   int             `json:"tickets_given_doorman"`
							TicketsRequirementMet bool            `json:"tickets_requirement_met"`
							Room                  map[string]bool `json:"room"`
							Phase                 struct {
								Current int `json:"current"`
							} `json:"phase"`
						} `json:"slumber"`
						UnderstandsStreaks                     bool `json:"understands_streaks"`
						CastleEntityExplosionFinalKillsBedwars int  `json:"castle_entity_explosion_final_kills_bedwars"`
					} `json:"bedwars"`
			} `json:"stats"`
		*/
		Stats any `json:"stats"`
	} `json:"player"`
}
