package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"server/internal/pkg/generated/models"
)

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, name string, password string, remember *bool) (*models.Signin, error) {
	panic(fmt.Errorf("not implemented: Signin - signin"))
}

// APIKey is the resolver for the apiKey field.
func (r *queryResolver) APIKey(ctx context.Context, name string, role string) (*models.Signin, error) {
	panic(fmt.Errorf("not implemented: APIKey - apiKey"))
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, name string) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Self is the resolver for the self field.
func (r *queryResolver) Self(ctx context.Context) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: Self - self"))
}
