package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"server/internal/pkg/generated/models"
)

// CreateDiscord is the resolver for the createDiscord field.
func (r *mutationResolver) CreateDiscord(ctx context.Context, id string, name string) (*models.Discord, error) {
	panic(fmt.Errorf("not implemented: CreateDiscord - createDiscord"))
}

// GiveXp is the resolver for the giveXp field.
func (r *mutationResolver) GiveXp(ctx context.Context, id string, amount int) (*models.Discord, error) {
	panic(fmt.Errorf("not implemented: GiveXp - giveXp"))
}

// Discord is the resolver for the discord field.
func (r *queryResolver) Discord(ctx context.Context, id string) (*models.Discord, error) {
	panic(fmt.Errorf("not implemented: Discord - discord"))
}
